// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA64ViTSIQbFPVvSDQC6LQycWM6CYMdYyw',
    appId: '1:884403957044:web:57f1a48c32ba9856d2c961',
    messagingSenderId: '884403957044',
    projectId: 'todoapp-85f5a',
    authDomain: 'todoapp-85f5a.firebaseapp.com',
    storageBucket: 'todoapp-85f5a.firebasestorage.app',
    measurementId: 'G-YDCLCMS6H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaB9sWpj-n6M0WkujshasVxgTLyCPX8dk',
    appId: '1:884403957044:android:0c6a95adc6511b59d2c961',
    messagingSenderId: '884403957044',
    projectId: 'todoapp-85f5a',
    storageBucket: 'todoapp-85f5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQaL1-L7aHv77_p-zHs1V4kB4WnsJMrM',
    appId: '1:884403957044:ios:3c6446baae7152d0d2c961',
    messagingSenderId: '884403957044',
    projectId: 'todoapp-85f5a',
    storageBucket: 'todoapp-85f5a.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUQaL1-L7aHv77_p-zHs1V4kB4WnsJMrM',
    appId: '1:884403957044:ios:3c6446baae7152d0d2c961',
    messagingSenderId: '884403957044',
    projectId: 'todoapp-85f5a',
    storageBucket: 'todoapp-85f5a.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA64ViTSIQbFPVvSDQC6LQycWM6CYMdYyw',
    appId: '1:884403957044:web:02e3eeb8c0b9be89d2c961',
    messagingSenderId: '884403957044',
    projectId: 'todoapp-85f5a',
    authDomain: 'todoapp-85f5a.firebaseapp.com',
    storageBucket: 'todoapp-85f5a.firebasestorage.app',
    measurementId: 'G-RLGG0E3LNE',
  );
}
